---
title: "Luciferase_Standard_Curve"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(data.table)
library(ggplot2)
```

```{r}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```

```{r}
convertAMP <- function (fit, value) {

intercept = signif(fit$coef[[1]],5 )
slope = signif(fit$coef[[2]], 5)
AMP = (value - intercept)/slope
return(AMP)
}
```

```{r DETECTR 011}

DETECTR_011 <- read.csv("../tidy_data/DETECTR_011_2hr_reporter_tidy.csv")

#get samples only

samples_011 <- subset(DETECTR_011, DETECTR_011$time=="02:00:00")

#plot
samples_011$rfu_value <- as.numeric(as.character(samples_011$rfu_value))

#avg_samples_011 <- samples_011 %>% group_by(gRNA, stock_conc, target_added) %>% summarize (mean_rfu_value = mean(rfu_value)) %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*1.5/(20*13)))

samples_011 <- samples_011 %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*5/(20),2))

pdf("../DETECTR_011_reporter_concentration.pdf", width = 6, height = 4)
ggplot(samples_011, aes(x = as.factor(final_conc), y = rfu_value, color= target_added, group = interaction(gRNA,target_added))) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_line(stat = "identity") +
  geom_point()+
  scale_color_manual(values = c("darkslategray3", "mediumpurple3","olivedrab4","darkseagreen3"))+
  ggtitle("DETECTR, 2 hour timepoint, reporter concentrations")+
  xlab("final concentration of reporter (uM) ")+
  ylab("RFU value (AU) ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold")
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()

pdf("../DETECTR_011_signal_to_noise_concentration.pdf", width = 6, height = 4)
ggplot(samples_011, aes(x = as.factor(final_conc), y = signal_to_noise, color= target_added, group = interaction(gRNA,target_added))) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_line(stat = "identity") +
  geom_point()+
  scale_color_manual(values = c("darkslategray3", "mediumpurple3","olivedrab4","darkseagreen3"))+
  ggtitle("DETECTR, 2 hour timepoint, reporter concentrations")+
  xlab("final concentration of reporter (uM) ")+
  ylab("signal to noise (target added/no target added) ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold")
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()


```

```{r DETECTR 014}
DETECTR_014 <- read.csv("../tidy_data/DETECTR_014_qPCR_temp_endpoint_tidy.csv")

#get samples only
#plot
DETECTR_014$rfu_value <- as.numeric(as.character(DETECTR_014$End.RFU))


pdf("../DETECTR_014_temperature.pdf", width = 6, height = 4)
ggplot(DETECTR_014, aes(x = temp, y = End.RFU, color= gRNA, group =  gRNA)) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_line(stat = "identity") +
  geom_point()+
  scale_color_manual(values = c("darkslategray3", "mediumpurple3","olivedrab4","darkseagreen3"))+
  ggtitle("DETECTR, 4 hour timepoint, temperature")+
  xlab("temperature of reaction (deg C)")+
  ylab("RFU value (AU) ")+
  scale_x_continuous(breaks=seq(30,45,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold")
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()


```

```{r DETECTR 016}
DETECTR_016 <- read.csv("../tidy_data/DETECTR_016_2hr_tidy.csv")

#get samples only

samples_016 <- subset(DETECTR_016, DETECTR_016$time=="02:00:00")

#plot
samples_016$rfu_value <- as.numeric(as.character(samples_016$rfu_value))

avg_samples_016 <- samples_016 %>% group_by(gRNA, stock_conc) %>% summarize (mean_rfu_value = mean(rfu_value)) %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*1.5/(20*13)))

samples_016 <- samples_016 %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*1.5*1000/(20*13)))

pdf("../DETECTR_016_crRNA_concentration.pdf", width = 6, height = 4)
ggplot(samples_016, aes(x = as.factor(final_conc), y = rfu_value, color= gRNA, group = gRNA)) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_line(stat = "identity") +
  geom_point()+
  scale_color_manual(values = c("darkslategray3", "mediumpurple3","olivedrab4","darkseagreen3"))+
  ggtitle("DETECTR, 2 hour timepoint, IVT guide RNAs")+
  xlab("final concentration of guide RNA (nM) ")+
  ylab("RFU value (AU) ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold")
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()


```





```{r DETECTR 017}


DETECTR_017 <- read.csv("../tidy_data/DETECTR_017_2hr_tidy.csv")

#get samples only

samples_017 <- subset(DETECTR_017, DETECTR_017$time=="02:00:00")

#plot
samples_017$rfu_value <- as.numeric(as.character(samples_017$rfu_value))

avg_samples_017 <- samples_017 %>% group_by(gRNA, stock_conc) %>% summarize (mean_rfu_value = mean(rfu_value)) %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*1.5/(20*13)))

samples_017 <- samples_017 %>% mutate (final_conc = round(as.numeric(as.character(stock_conc))*1.5*1000/(20*13)))

pdf("../DETECTR_017_IVT_vs_synthetic.pdf", width = 6, height = 4)
ggplot(samples_017, aes(x = as.factor(final_conc), y = rfu_value, color= gRNA, group = interaction(gRNA, row_384))) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_point(stat = "identity") +
  geom_line()+
  scale_color_manual(values = c("darkslategray3", "mediumpurple3","yellow","blue"))+
  ggtitle("DETECTR, 2 hour timepoint, IVT vs Synthetic")+
  xlab("final concentration of guide RNA (nM) ")+
  ylab("average RFU value (AU) ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold"),
        legend.title = element_blank()
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()


```


```{r DETECTR 018}

DETECTR_018 <- read.csv("../tidy_data/DETECTR_018_tidy_metadata.csv")

#get samples only

samples_018 <- subset(DETECTR_018, DETECTR_018$time=="02:00:00")

#plot
samples_018$rfu_value <- as.numeric(as.character(samples_018$rfu_value))
samples_018$stock_conc <- as.factor(samples_018$stock_conc)
samples_018$replicate_sample <- paste(as.character(samples_018$stock_conc), as.character(samples_018$replicate))

avg_samples_018 <- samples_018 %>% group_by(stock_conc, target_DNA) %>% summarize (mean_rfu_value = mean(rfu_value)) %>% mutate (final_conc = as.numeric(as.character(stock_conc))/20)

pdf("../DETECTR_018_gDNA_contamination.pdf", width = 6, height = 4)
ggplot(avg_samples_018, aes(x = stock_conc, y = mean_rfu_value, fill = target_DNA)) +
  #facet_wrap(~target_DNA,scales = "free_x")+
  geom_bar(stat = "identity",position = 'dodge') +
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3","yellow","blue"))+
  ggtitle("DETECTR, 2 hour timepoint, gDNA contamination")+
  xlab("input mass of HEK 293 gDNA (ng) ")+
  ylab("average RFU value (AU) ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold"),
        legend.title = element_blank()
        #strip.background = element_rect(fill = NA, color = "black"),
        #strip.text = element_text(size = 10)
) 
dev.off()

```


```{r DETECTR 020}

DETECTR_020 <- read.csv("../tidy_data/DETECTR_020_tidy_metadata.csv")

  
standard_020 <- subset(DETECTR_020, DETECTR_020$time=="01:00:00" & DETECTR_020$sample_set=="standard_in_buffer")
standard_020$standard_conc <- as.numeric(as.character(standard_020$standard_conc))
ggplotRegression(lm(standard_020$rfu_value~standard_020$standard_conc))

#convert rfu_value to AMP
DETECTR_020$AMP <- convertAMP(lm(standard_020$rfu_value~standard_020$standard_conc), DETECTR_020$rfu_value)
#get samples only
samples_020 <- subset(DETECTR_020, DETECTR_020$time=="01:00:00" & DETECTR_020$gRNA_used!="standard" & DETECTR_020$sample_set!="no_sample")

#RPA_samples_020$target_added <- factor(RPA_samples_020$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
samples_020$AMP <- as.numeric(as.character(samples_020$AMP))

pdf("../DETECTR_020_NANCYDREW_firsttest.pdf", width = 6, height = 4)
ggplot(samples_020, aes(x = sample_set, y = AMP, fill = replicate)) +
  facet_wrap(~gRNA_used,ncol=4,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","blue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()


samples_020_avg <- samples_020  %>% group_by(sample_set, gRNA_used) %>% summarize (mean_AMP_value = mean(AMP)) 
pdf("../DETECTR_020_NANCYDREW_firsttest_average.pdf", width = 6, height = 4)
ggplot(samples_020_avg, aes(x = gRNA_used, y = mean_AMP_value, fill = sample_set)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","blue"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+
  ylab("average AMP (uM)")+
  xlab("guide RNA/target DNA")+
  ggtitle("NANCY DREW, 12 hour timepoint, 25nM target concentration")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10),
        legend.title = element_blank()
) 
dev.off()

```

```{r DETECTR 021}

DETECTR_021 <- read.csv("../tidy_data/DETECTR_021_tidy_metadata.csv")

  
standard_021 <- subset(DETECTR_021, DETECTR_021$time=="01:00:00" & DETECTR_021$sample_set=="standard")
standard_021$standard_conc <- as.numeric(as.character(standard_021$standard_conc))
ggplotRegression(lm(standard_021$rfu_value~standard_021$standard_conc))

#convert rfu_value to AMP
DETECTR_021$AMP <- convertAMP(lm(standard_021$rfu_value~standard_021$standard_conc), DETECTR_021$rfu_value)
#get samples only
samples_021 <- subset(DETECTR_021, DETECTR_021$time=="01:00:00" & DETECTR_021$gRNA_used!="standard" & DETECTR_021$sample_set!="no_sample"& DETECTR_021$sample_set!="degraded_target")

#RPA_samples_021$target_added <- factor(RPA_samples_021$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
samples_021$AMP <- as.numeric(as.character(samples_021$AMP))
pdf("../DETECTR_021_crRNAtests.pdf",width = 6, height = 6)
ggplot(samples_021, aes(x = sample_set, y = AMP, fill = replicate)) +
  facet_wrap(~gRNA_description,ncol=3,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","mediumorchid4"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+

  ylab("AMP (uM)")+
  ggtitle("NANCY DREW, 12 hour timepoint, crRNA tests")+
  theme(#axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        axis.text.x = element_blank(),
        title = element_text(face = "bold"),
        
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 8)
) 
dev.off()

samples_021_avg <- samples_021  %>% group_by(sample_set, gRNA_description) %>% summarize (mean_AMP_value = mean(AMP)) 
samples_021_avg_1 <- subset(samples_021_avg, gRNA_description %in% c("guide with 2Cs","guide with 3Cs", "guide with 5As before 2Cs"))
pdf("../DETECTR_021_crRNAtests_average_1.pdf",width = 6, height = 3)
ggplot(samples_021_avg_1, aes(x = sample_set, y = mean_AMP_value, fill = sample_set)) +
  facet_wrap(~gRNA_description,ncol=3,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","mediumorchid4"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+

  ylab("average AMP (uM)")+
  ggtitle("NANCY DREW, 12 hour timepoint, crRNA tests")+
  theme(#axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        axis.text.x = element_blank(),
        title = element_text(face = "bold"),
        
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 8)
) 
dev.off()

samples_021_avg_2 <- subset(samples_021_avg, gRNA_description %in% c("IVT guide","synthetic guide"))
pdf("../DETECTR_021_crRNAtests_average_2.pdf",width = 6, height = 3)
ggplot(samples_021_avg_2, aes(x = sample_set, y = mean_AMP_value, fill = sample_set)) +
  facet_wrap(~gRNA_description,ncol=3,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","mediumorchid4"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+

  ylab("average AMP (uM)")+
  theme(
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        axis.text.x = element_blank(),
        title = element_text(face = "bold"),
        
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 8)
) 
dev.off()


```

```{r DETECTR 024}

DETECTR_024 <- read.csv("../tidy_data/DETECTR_024_Luciferase_tidy_metadata.csv")

  
standard_024 <- subset(DETECTR_024, DETECTR_024$time=="01:00:00" & DETECTR_024$sample_set=="standard")
standard_024$standard_conc <- as.numeric(as.character(standard_024$standard_conc))
ggplotRegression(lm(standard_024$rfu_value~standard_024$standard_conc))

#convert rfu_value to AMP
DETECTR_024$AMP <- convertAMP(lm(standard_024$rfu_value~standard_024$standard_conc), DETECTR_024$rfu_value)
#get samples only
samples_024 <- subset(DETECTR_024, DETECTR_024$time=="01:00:00" & DETECTR_024$sample_set!="standard")

#RPA_samples_024$target_added <- factor(RPA_samples_024$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
samples_024$AMP <- as.numeric(as.character(samples_024$AMP))
pdf("../DETECTR_024_DNA-RNA_12hour.pdf", width = 6, height = 4)
ggplot(samples_024, aes(x = sample_set, y = rfu_value, fill = replicate)) +
  facet_wrap(~gRNA_used,ncol=4,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","yellow","blue"))+
  ggtitle("NANCY DREW, 12 hour timepoint, DNA-RNA hybrid reporter")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 

dev.off()

samples_024$AMP <- as.numeric(as.character(samples_024$AMP))

samples_024_average <- samples_024 %>% group_by(sample_set, gRNA_used) %>% summarize (mean_AMP_value=mean(AMP))
samples_024_average_subset <- subset(samples_024_average, gRNA_used %in% c("IVT_11C","syn_11C"))

pdf("../DETECTR_024_DNA-RNA_12hour_average.pdf", width = 6, height = 4)
ggplot(samples_024_average_subset, aes(x = sample_set, y = mean_AMP_value, fill = sample_set)) +
  facet_wrap(~gRNA_used,ncol=4,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","hotpink3","blue"))+
  ggtitle("NANCY DREW, 12 hour timepoint, DNA-RNA hybrid reporter")+
  ylab("average AMP (uM)")+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+

  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 

        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10),
        legend.title = element_blank()
) 

dev.off()

```


```{r DETECTR 024}

DETECTR_024 <- read.csv("../tidy_data/DETECTR_024_FAM_tidy_metadata.csv")

#get samples only

samples_024 <- subset(DETECTR_024, DETECTR_024$time=="12:00:00")
#plot


samples_024$rfu_value <- as.numeric(as.character(samples_024$rfu_value))
pdf("../DETECTR_024_DNA-FAM_Control_12hour.pdf", width = 6, height = 4)
ggplot(samples_024, aes(x = sample_set, y = rfu_value, fill = replicate)) +
  facet_wrap(~gRNA_used,ncol=4,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3","darkseagreen3"))+
  ggtitle("DETECTR control for NANCY DREW, 12 hour timepoint")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()

samples_024$rfu_value <- as.numeric(as.character(samples_024$rfu_value))

samples_024_average <- samples_024 %>% group_by(sample_set, gRNA_used) %>% summarize (mean_rfu_value = mean (rfu_value))
samples_024_average_subset <- subset(samples_024_average, gRNA_used %in% c("IVT_11C","syn_11C"))

pdf("../DETECTR_024_DNA-FAM_Control_12hour_average.pdf", width = 6, height = 4)
ggplot(samples_024_average_subset, aes(x = sample_set, y = mean_rfu_value, fill = sample_set)) +
  facet_wrap(~gRNA_used,ncol=4,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3","darkseagreen3"))+
  ggtitle("DETECTR control for NANCY DREW, 12 hour timepoint")+
  ylab("average RFU value (AU)")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10),
        legend.title = element_blank()
) 
dev.off()

```

```{r DETECTR 025}

DETECTR_025 <- read.csv("../tidy_data/DETECTR_025_tidy_metadata.csv")

  
standard_025 <- subset(DETECTR_025, DETECTR_025$time=="01:00:00" & DETECTR_025$reporter=="standard")
standard_025$standard_conc <- as.numeric(as.character(standard_025$standard_conc))
ggplotRegression(lm(standard_025$rfu_value~standard_025$standard_conc))

#convert rfu_value to AMP
DETECTR_025$AMP <- convertAMP(lm(standard_025$rfu_value~standard_025$standard_conc), DETECTR_025$rfu_value)
#get samples only
samples_025 <- subset(DETECTR_025, DETECTR_025$time=="01:00:00" & DETECTR_025$reporter!="standard")

#RPA_samples_025$target_added <- factor(RPA_samples_025$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
samples_025$AMP <- as.numeric(as.character(samples_025$AMP))
samples_025 <- subset(samples_025,degradation_method %in% c("DNAse1","none","RNAseH"))

pdf("../DETECTR_025_DNAse1_RNAseH_Experiment.pdf",width = 6, height = 4)
ggplot(samples_025, aes(x = reporter, y = AMP, fill = replicate)) +
  facet_grid(RNAseT~degradation_method,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2","yellow","blue"))+
    scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 

dev.off()

```



```{r DETECTR 026}
DETECTR_026 <- read.csv("../tidy_data/DETECTR_026_tidy_metadata.csv")

  
standard_026 <- subset(DETECTR_026, DETECTR_026$time=="01:00:00" & DETECTR_026$reporter=="standard")
standard_026$standard_conc <- as.numeric(as.character(standard_026$standard_conc))
ggplotRegression(lm(standard_026$rfu_value~standard_026$standard_conc))

#convert rfu_value to AMP
DETECTR_026$AMP <- convertAMP(lm(standard_026$rfu_value~standard_026$standard_conc), DETECTR_026$rfu_value)
#get samples only
samples_026 <- subset(DETECTR_026, DETECTR_026$time=="01:00:00" & DETECTR_026$reporter!="standard"& DETECTR_026$reporter!=""& DETECTR_026$sample_set!="DNAse1")

#RPA_samples_026$target_added <- factor(RPA_samples_026$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
samples_026$AMP <- as.numeric(as.character(samples_026$AMP))
samples_026$sample_name <- paste(samples_026$reporter,"_", samples_026$RNAseT,"_",samples_026$reporter_conc,samples_026$replicate)
samples_026$sample_name <- factor(samples_026$sample_name, levels = c("DNA-RNA _ RNAseT_added _ 45 a","DNA-RNA _ RNAseT_added _ 45 b","DNA-RNA _ RNAseT_added _ 15 a","DNA-RNA _ RNAseT_added _ 15 b","DNA-RNA _ RNAseT_added _ 5 a","DNA-RNA _ RNAseT_added _ 5 b","DNA-RNA _ RNAseT_added _ 1.66 a" , "DNA-RNA _ RNAseT_added _ 1.66 b","DNA-RNA _ RNAseT_added _ 0.833 a", "DNA-RNA _ RNAseT_added _ 0.833 b","DNA-RNA _ RNAseT_added _ 0 a","DNA-RNA _ RNAseT_added _ 0 b","DNA-RNA _ no_RNAseT _ 45 a" ,"DNA-RNA _ no_RNAseT _ 45 b","RNA _ RNAseT_added _ 45 a" , "RNA _ RNAseT_added _ 45 b"   ))
pdf("../DETECTR_026_DNA-RNAdigestion_differentbuffers.pdf", width = 6, height = 5)
ggplot(samples_026, aes(x = sample_name, y = AMP, fill = sample_set)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+
  ggtitle("Digestion of DNA-RNA reporter in different buffers")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()





samples_026_avg <- samples_026 %>% group_by(sample_set, RNAseT, reporter, reporter_conc) %>% summarize (mean_AMP_value = mean(AMP))

samples_026_avg$sample_set <- plyr::revalue(samples_026_avg$sample_set, c("2XBB"="Doudna Buffer","H20"="NEB Buffer"))
samples_026_avg$RNAseT <- factor(samples_026_avg$RNAseT, levels = c("RNAseT_added","no_RNAseT"))
pdf("../DETECTR_026_DNA-RNAdigestion_differentbuffers_average.pdf", width = 7, height = 4)
ggplot(samples_026_avg, aes(x = as.factor(reporter_conc), y = mean_AMP_value, fill = sample_set)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  facet_wrap(reporter~RNAseT,drop = TRUE, scale = "free_x")+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+
  ggtitle("Digestion of DNA-RNA reporter in different buffers")+
  ylab("average AMP (uM)")+
  xlab("reporter concentration (uM)")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()

```


```{r DETECTR 027}
#read in DETECTR data
DETECTR_027 <- read.csv("../tidy_data/DETECTR_027_tidy_metadata.csv")

#get samples only
RPA_samples_027 <- subset(DETECTR_027, DETECTR_027$time=="01:00:00" & DETECTR_027$sample_set!="2XBB"& DETECTR_027$sample_set!="NEB2.1")


RPA_samples_027$target_added <- factor(RPA_samples_027$target_added, levels = c("RPA_2_B1_16srRNA_10ng","RPA_2_B1_16srRNA_0.1ng","RPA_2_B1_16srRNA_0ng", "RPA_48_H6_IS1081_10ng", "RPA_48_H6_IS1081_0.1ng", "RPA_48_H6_IS1081_0ng","synthetic_B1","synthetic_H6","no_target"))

#plot
RPA_samples_027$rfu_value <- as.numeric(as.character(RPA_samples_027$rfu_value))
pdf("DETECTR_027_RPAproducts.pdf", width = 6, height = 4)
ggplot(RPA_samples_027, aes(x = target_added, y = rfu_value, fill = replicate)) +
  facet_wrap(~sample_set,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  ggtitle("DETECTR, 1 hour timepoint")+
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3","yellow","blue"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()

RPA_samples_027_unpurified <- subset(RPA_samples_027, sample_set == "unpurified")

RPA_samples_027_unpurified_avg <- RPA_samples_027_unpurified %>% group_by(target_added, gRNA_used) %>% summarize (mean_rfu_value = mean(rfu_value)) 

RPA_samples_027_unpurified_avg$input_conc <- factor(c("10ng","0.1ng","0ng","10ng","0.1ng","0ng"), levels = c("10ng","0.1ng","0ng"))

pdf("DETECTR_027_RPAproducts_template_conc.pdf", width = 6, height = 4)

ggplot(RPA_samples_027_unpurified_avg, aes(x = gRNA_used, y = mean_rfu_value, fill = input_conc)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  ggtitle("DETECTR, 1 hour timepoint")+
  scale_fill_manual(name = "input mass",values = c("darkslategray3", "mediumpurple3","darkseagreen3","blue"))+
  ylab("average RFU value (AU)")+
  xlab("guide RNA/target DNA")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()
        
```



```{r DETECTR 028}
#read in DETECTR data
DETECTR_028 <- read.csv("../tidy_data/DETECTR_028_Luciferase_tidy_metadata.csv")

#calculate standard curve based on 1hr mark
standard_028 <- subset(DETECTR_028, DETECTR_028$time=="01:00:00" & DETECTR_028$sample_set=="standard")
standard_028$standard_conc <- as.numeric(as.character(standard_028$standard_conc))
ggplotRegression(lm(standard_028$rfu_value~standard_028$standard_conc))

#convert rfu_value to AMP
DETECTR_028$AMP <- convertAMP(lm(standard_028$rfu_value~standard_028$standard_conc), DETECTR_028$rfu_value)

#get samples only
samples_028 <- subset(DETECTR_028, DETECTR_028$time=="01:00:00" & DETECTR_028$sample_set!="standard"& DETECTR_028$sample_set!=""& DETECTR_028$reporter!="DNA-RNA/r17A-TTATT-r3C"& DETECTR_028$reporter!="RNA/r17Ar3C")
#plot


pdf("../DETECTR_028_phos_reporter.pdf", width = 6, height = 4)
ggplot(samples_028, aes(x = sample_set, y = AMP, fill = replicate)) +
  facet_wrap(~reporter,ncol=4,drop = TRUE,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(breaks=seq(0,10,2), limits=c(0,10), expand = c(0,0))+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  ylab("AMP (uM)")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        #strip.background = element_rect(color="black", fill="grey", size=1.5, linetype="solid"),
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()



#get samples only
samples_028 <- subset(DETECTR_028, DETECTR_028$time=="01:00:00" & DETECTR_028$sample_set!="standard"& DETECTR_028$sample_set!=""& DETECTR_028$reporter!="DNA-RNA/r17A-TTATT-r3C"& DETECTR_028$reporter=="RNA/r17Ar3C")
#plot
samples_028

pdf("../DETECTR_028_NANCYDREW_firsttime.pdf", width = 6, height = 4)
ggplot(samples_028, aes(x = sample_set, y = AMP, fill = replicate)) +
  #facet_wrap(~reporter,ncol=4,drop = TRUE,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(breaks=seq(0,10,2), limits=c(0,10), expand = c(0,0))+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  ylab("AMP (uM)")+
  ggtitle("NANCY DREW, 3 hour timepoint, 500nM input")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        #strip.background = element_rect(color="black", fill="grey", size=1.5, linetype="solid"),
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()

samples_028_average <- samples_028 %>% group_by(sample_set) %>% summarize (mean_AMP_value = mean(AMP))
samples_028_average$sample_set<-as.character(samples_028_average$sample_set)

samples_028_average$sample_set <- plyr::revalue(samples_028_average$sample_set , c("synthetic-11C"="target_added"))
pdf("../DETECTR_028_NANCYDREW_firsttime_average.pdf", width = 6, height = 4)
ggplot(samples_028_average, aes(x = sample_set, y = mean_AMP_value)) +
  #facet_wrap(~reporter,ncol=4,drop = TRUE,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge', fill = "coral2") +
  scale_y_continuous(breaks=seq(0,10,2), limits=c(0,10), expand = c(0,0))+
  scale_fill_manual(values = c("coral2"))+
  ylab("average AMP (uM)")+
  ggtitle("NANCY DREW, 3 hour timepoint, 25nM target concentration")+
  scale_y_continuous(breaks=seq(0,10,2), limits=c(-0.5,10), expand = c(0,0))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        #strip.background = element_rect(color="black", fill="grey", size=1.5, linetype="solid"),
        axis.title.x=element_blank(),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
) 
dev.off()
```

```{r DETECTR 029}
#read in DETECTR data
DETECTR_029 <- read.csv("../tidy_data/DETECTR_029_tidy_metadata.csv")

#calculate standard curve based on 1hr mark
standard_029 <- subset(DETECTR_029, DETECTR_029$time=="01:00:00" & DETECTR_029$sample_set=="standard")
standard_029$input_conc <- as.numeric(as.character(standard_029$input_conc))
ggplotRegression(lm(standard_029$rfu_value~standard_029$input_conc))

#convert rfu_value to AMP
DETECTR_029$AMP <- convertAMP(lm(standard_029$rfu_value~standard_029$input_conc), DETECTR_029$rfu_value)

#get samples only
samples_029 <- subset(DETECTR_029, DETECTR_029$time=="01:00:00" & DETECTR_029$sample_set!="standard")
#plot
samples_029$input_conc <-droplevels(samples_029$input_conc)
samples_029$input_conc <- factor(samples_029$input_conc, levels=c("5uM","500nM","50nM","5nM","500pM","50pM","5pM","500fM","50fM","5fM","no_target","no_cas12a"))

pdf("../DETECTR_029_NANCYDREW_LOD.pdf", width = 6, height = 4)
ggplot(samples_029, aes(x = input_conc, y = AMP, fill = replicate)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(breaks=seq(0,10,2), limits=c(0,10), expand = c(0,0))+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  ggtitle("NANCY DREW, Limit of Detection\n10X Dilution Series, 3 hour timepoint")+
  ylab("AMP (uM)")+
  theme(axis.text.x = element_text(angle = 90), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
)

dev.off()

samples_029_average <- samples_029 %>% group_by(input_conc) %>% summarize (mean_AMP_value = mean(AMP))
samples_029_average$final_conc <- factor(c("500nM","50nM","5nM","500pM","50pM","5pM","500fM","50fM","5fM","500aM","no_target","no_cas12a"), levels=c("500nM","50nM","5nM","500pM","50pM","5pM","500fM","50fM","5fM","500aM","no_target","no_cas12a"))

pdf("../DETECTR_029_NANCYDREW_LOD_average.pdf", width = 6, height = 4)
ggplot(samples_029_average, aes(x = final_conc, y = mean_AMP_value)) +
  geom_bar(stat = 'identity', position = 'dodge', fill = "coral2") +
  scale_y_continuous(breaks=seq(0,10,2), limits=c(0,10), expand = c(0,0))+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  ggtitle("NANCY DREW, Limit of Detection\n10X Dilution Series, 3 hour timepoint")+
  ylab("average AMP (uM)")+
  xlab("target DNA final concentration")+
 
  theme(axis.text.x = element_text(angle = 60, hjust=1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10)
)

dev.off()
        
```


```{r DETECTR 030}
#read in DETECTR data
DETECTR_030 <- read.csv("../tidy_data/DETECTR_030_tidy_metadata.csv")

#get 3 hour samples only
samples_030 <- subset(DETECTR_030, DETECTR_030$time=="03:00:00")
#plot
samples_030$input_conc <-droplevels(samples_030$input_conc)
samples_030$input_conc <- factor(samples_030$input_conc, levels=c("5uM","500nM","50nM","5nM","500pM","50pM","5pM","500fM","50fM","5fM","no_target","no_cas12a"))

ggplot(samples_030, aes(x = input_conc, y = rfu_value, fill = replicate)) +
  facet_wrap(~reporter)+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3"))+
  theme(axis.text.x = element_text(angle = 90), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black")
)

RNA_average <- samples_030 %>% filter(reporter == "RNA-FAM" & input_conc %in% c("no_target","no_cas12a")) %>% summarize (mean = mean(rfu_value))

DNA_average <- samples_030 %>% filter(reporter == "DNA-FAM" & input_conc %in% c("no_target","no_cas12a")) %>% summarize (mean = mean(rfu_value))



DNA_030 <- samples_030 %>% filter (reporter == "DNA-FAM") %>% plyr::mutate(bckground_sub_rfu = rfu_value - as.numeric(DNA_average))

RNA_030 <- samples_030 %>% filter (reporter == "RNA-FAM") %>% plyr::mutate(bckground_sub_rfu = rfu_value - as.numeric(RNA_average))

samples_030 <- merge(DNA_030,RNA_030, all = TRUE)


samples_030_average <- samples_030 %>% group_by(input_conc,reporter) %>% summarize (mean_rfu_value = mean(bckground_sub_rfu))
samples_030_average$final_conc <- factor(c("500nM","500nM","50nM","50nM","5nM","5nM","500pM","500pM","50pM","50pM","5pM","5pM","500fM","500fM","50fM","50fM","5fM","5fM","500aM","500aM","no_target","no_target","no_cas12a","no_cas12a"), levels=c("500nM","50nM","5nM","500pM","50pM","5pM","500fM","50fM","5fM","500aM","no_target","no_cas12a"))

pdf("../DETECTR_030_RNA_DNA_LOD_average.pdf", width = 6, height = 4)
ggplot(samples_030_average, aes(x = final_conc, y = mean_rfu_value, fill = reporter)) +
  facet_wrap(~reporter)+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(expand = c(0,0))+
  ggtitle("DETECTR (no RPA), Limit of Detection\n10X Dilution Series, 3 hour timepoint")+
  scale_fill_manual(values = c("darkslategray3", "mediumpurple3"))+
  ylab("average background subtracted RFU (AU)") +
    xlab("target DNA final concentration")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"),
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 10),
        legend.position = "none"
          
        
)
dev.off()
        
```

```{r DETECTR 031}
#read in DETECTR data
DETECTR_031 <- read.csv("../tidy_data/DETECTR_031_tidy_metadata.csv")

#calculate standard curve based on 1hr mark
standard_031 <- subset(DETECTR_031, DETECTR_031$time=="00:50:00" & DETECTR_031$reporter=="standard")
standard_031$standard_conc <- as.numeric(as.character(standard_031$standard_conc))
ggplotRegression(lm(standard_031$rfu_value~standard_031$standard_conc))

#convert rfu_value to AMP
DETECTR_031$AMP <- convertAMP(lm(standard_031$rfu_value~standard_031$standard_conc), DETECTR_031$rfu_value)

#get samples only
samples_031 <- subset(DETECTR_031, DETECTR_031$time=="00:50:00" & DETECTR_031$reporter!="standard"& DETECTR_031$reporter!=""& DETECTR_031$reporter!="H20")
samples_031$sample_set <- samples_031$standard_conc
#plot
samples_028 <- subset(DETECTR_028, DETECTR_028$time=="01:00:00" & DETECTR_028$sample_set!="standard"& DETECTR_028$sample_set!=""& DETECTR_028$reporter!="DNA-RNA/r17A-TTATT-r3C"& DETECTR_028$reporter!="RNA/r17Ar3C"& DETECTR_028$sample_set!="no_target")
samples_028$reporter_nickname <- samples_028$reporter

samples_028_031 <- merge(samples_031,samples_028, all = TRUE)
samples_028_031$RNAseT <- plyr::revalue(samples_028_031$RNAseT , c("no_RNAse_T_added"="no_RNAseT"))
samples_028_031$RNAseT <- plyr::revalue(samples_028_031$RNAseT , c("no_RNAseT_added"="no_RNAseT"))

samples_028_031$RNAseT <- plyr::revalue(samples_028_031$RNAseT , c("RNAse_T_added"="RNAseT_added"))
samples_028_031$RNAseT <- plyr::revalue(samples_028_031$RNAseT , c("RNAse_T"="RNAseT_added"))
samples_028_031$sample_set <- plyr::revalue(samples_028_031$sample_set , c("no_RNAseT"="45uM"))


samples_028_031$reporter_nickname <- plyr::revalue(samples_028_031$reporter_nickname , c("r5A-GGAGG-nophos"="r5A-DNA-nophos"))
samples_028_031$reporter_nickname <- plyr::revalue(samples_028_031$reporter_nickname , c("r5A-GGAGG-phos"="r5A-DNA-phos"))

samples_028_031$reporter_nickname <- factor(samples_028_031$reporter_nickname, levels = c("r5A-DNA-Gs","r5A-DNA-Cs","r5A-DNA-PT","r5A-DNA-ddC","r5A-DNA-nophos","r5A-DNA-phos"))

samples_028_031_avg <- samples_028_031 %>% group_by(RNAseT,reporter_nickname,sample_set) %>% summarize (mean_AMP_value = mean (AMP))

pdf("../DETECTR_031_028_modified_reporter_avg.pdf", width = 8, height = 4)
ggplot(samples_028_031_avg, aes(x = sample_set, y = mean_AMP_value, fill = sample_set)) +
  facet_grid(RNAseT~reporter_nickname,drop = TRUE,scales = "free_x")+
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_y_continuous(breaks=seq(0,12,2), limits=c(-1,13), expand = c(0,0))+
  scale_fill_manual(values = c("coral2", "goldenrod2"))+
  ylab("average AMP (uM)")+
  xlab("reporter concentration")+
  ggtitle("3' blocked reporters, varying concentrations")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey"),
        panel.border = element_rect(fill = NA, color = "black"), 
        #strip.background = element_rect(color="black", fill="grey", size=1.5, linetype="solid"),
   
        title = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, color = "black"),
        strip.text = element_text(size = 9),
        legend.position = "none"
) 
dev.off()
```





